version: '3'
services:
  db:
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exercisedb
    ports:
      - "5432:5432"

  java:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: exercisedb
      DB_USER: postgres
      DB_PASSWORD: example

    ports:
      - "8080:8080"

